mysql:
  image: mysql:8.0
  container_name: mysql
  environment:
    MYSQL_USER: "matheus"
    MYSQL_PASSWORD: "1234"
    MYSQL_ROOT_PASSWORD: "1234"
  ports:
    - "3306:3306"
  volumes:
    - ./db:/var/lib/mysql
